PR chrome backend
NCKU-CCS/fake-info-backend pull request #4
Opened 2021-04-14 17:39 UTC by williron3960

2021-04-15 09:58 UTC, iknowright commented on .env
> +POSTGRES_DB=new_postgres
`.env` 還是被 push 上來了，可以參考 [link](https://devconnected.com/how-to-clear-git-cache/) 解決這個問題，
也就是說，以前可能已經把檔案丟上 git 了，但後來要把它給移除（加進 `.gitignore` , 就要這樣)

2021-04-15 10:01 UTC, iknowright commented on docker-compose.yml
> +    volumes:
[疑問] 加入 volume 的必要性是如何？

對了補充說明， dockerize api, 是可以作為 production 之用， 所以把 source code 掛在 volume 還想沒意義

2021-04-15 10:02 UTC, iknowright commented on docker-compose.yml
> +    command: bash -c "pipenv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
dockerize api 不需要 `--reload`, 要把 dockerize 的 image 當做 ready 好的

2021-04-15 10:08 UTC, williron3960 commented on .env
> +POSTGRES_DB=new_postgres
抱歉這邊我有點不太清楚，我目前有先將.env加進gitignore ，是要再remove .env嗎，這樣會不會你們讀不到這個檔案。

2021-04-15 10:10 UTC, iknowright commented on Pipfile
> +starlette = "*"
應該有說過，可以把 version 都 hard code 在上面~

2021-04-15 10:11 UTC, williron3960 commented on Pipfile
> +starlette = "*"
放到忘記了ＸＤ 馬上補

2021-04-15 10:12 UTC, iknowright commented on README.md
> +* git clone https://github.com/NCKU-CCS/fake-info-backend
這兩行可以不用加進去， 架設使用者已經從 github 看到你的資源了，應該就會在你這這目錄底下進行操作

當然，如果可以加入更多文字會更好

2021-04-15 10:13 UTC, iknowright commented on docker-compose.yml
> +      - "5432:5432"
因為使用 pipenv 可以改成 `${PORT}:5432`

2021-04-15 11:34 UTC, iknowright requested changes
有些地方要修正，麻煩再看一下咯~

2021-04-15 11:39 UTC, iknowright commented on .env
> +POSTGRES_DB=new_postgres
啊 對，這部分忘記說清楚了:
本身， `.env` 就是一個比較動態的一些參數，這就是為什麼我們用 environment variable 來處理，但這些東西我們又不希望放在 git, 因為有時候 .env 會有一些 secret 的資料。

解決辦法：
因為我們不要 .env 在 git, 但是我們可以開一個 `sameple.env` 放到 git, 它的內容可以像是

```
SECRET_KEY=xxxx
POSTGRES_USER=yourname
POSTGRES_PASSWORD=yourpassword
POSTGRES_SERVER=yourserver
POSTGRES_PORT=yourport
POSTGRES_DB=yourdb
```

也可以直接 xxx, 或者**把 Value 留空**, 這樣一來，下一個使用你 repo 的人就知道，原來我需要設定一些屬於我自己的參數，基於這個 `sample.env` (後來他可以 rename 變成 `.env`)

2021-04-15 15:14 UTC, williron3960 commented on .env
> +POSTGRES_DB=new_postgres
原來，那我應該要在本地端也留一個我自己看的正確密碼，然後傳給協作者，我理解了，感謝！

2021-04-16 01:46 UTC, iknowright requested changes
記得每次發 pr 都要注意一下規範

2021-04-16 03:17 UTC, williron3960 commented
@iknowright  感謝你，我大致上將review的問題解決了，
last line 那個在commit 554e29c有解決，
對了，我想問說要把中間的commit rebase起來嗎，
這樣比較方便你review，謝謝。

2021-04-16 07:15 UTC, iknowright commented
> @iknowright 感謝你，我大致上將review的問題解決了，
> last line 那個在commit 554e29c有解決，
> 對了，我想問說要把中間的commit rebase嗎，
> 這樣比較方便你review，謝謝。

需要哦， 把類似合在一起，但不要整個合在一起

2021-04-16 07:17 UTC, iknowright approved these changes
LGTM

2021-04-16 16:37 UTC, Darkborderman commented on README.md
> +
可以補一下是怎麼建立環境的喔

`prerequisite` typo, 另外應該也有pipenv 要補上

2021-04-18 14:51 UTC, merged